<?php

function shift_cipher_menu() {
    $items = array();
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
    );
    $items['cipher_success'] = array(
        'title' => 'Shift Cipher Results Page',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'shift_cipher_success',
    );
    return $items;
}

function shift_cipher_form() {
    $form = array();
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('The number of places to shift over each letter.'),
        // '#element_validate' => array('element_validate_integer_positive', 'element_validate_shift_range'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Choose to shift either right or left.'),
        // '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['cipher_phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please choose a phrase to encrypt.'),
        // '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );
    return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['shift_direction'];
    $phrase = strtolower($form_state['values']['cipher_phrase']);
    $phrase_array = str_split($phrase);

    $alphabet = array(
        '0' => 'a',
        '1' => 'b',
        '2' => 'c',
        '3' => 'd',
        '4' => 'e',
        '5' => 'f',
        '6' => 'g',
        '7' => 'h',
        '8' => 'i',
        '9' => 'j',
        '10' => 'k',
        '11' => 'l',
        '12' => 'm',
        '13' => 'n',
        '14' => 'o',
        '15' => 'p',
        '16' => 'q',
        '17' => 'r',
        '18' => 's',
        '19' => 't',
        '20' => 'u',
        '21' => 'v',
        '22' => 'w',
        '23' => 'x',
        '24' => 'y',
        '25' => 'z',
    );

    $new_phrase = array();

    for($i = 0; $i < count($phrase_array); $i++) {
        if (ctype_alpha($phrase_array[$i])){
            if ($direction === 'right') {
                foreach($alphabet as $key => $value) {
                    if ($value === $phrase_array[$i]) {
                        $shift_reference = $key + $shift_value;
                        if ($shift_reference > 25) {
                            $shift_reference = $shift_reference - 26;
                            array_push($new_phrase, $alphabet[$shift_reference]);
                        } else array_push($new_phrase, $alphabet[$shift_reference]);
                    }
                }
            } else {
                foreach($alphabet as $key => $value) {
                    if ($value === $phrase_array[$i]) {
                        $shift_reference = $key - $shift_value;
                        if ($shift_reference < 0) {
                            $shift_reference = $shift_reference + 26;
                            array_push($new_phrase, $alphabet[$shift_reference]);
                        } else array_push($new_phrase, $alphabet[$shift_reference]);
                    }
                }

            }
        } else array_push($new_phrase, $phrase_array[$i]);
    }

    $new_phrase = implode("", $new_phrase);


    $_SESSION['shift_cypher_output'] = $new_phrase;
    $form_state['redirect'] = 'cipher_success';
}

function shift_cipher_success() {
    $results = $_SESSION['shift_cypher_output'];
    return $results;
}
