<?php

function shift_cipher_menu() {
    $items = array();
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
    );
    $items['cipher_success'] = array(
        'title' => 'Shift Cipher Results Page',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'shift_cipher_success',
    );
    return $items;
}

function shift_cipher_form() {
    $form = array();
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('The number of places to shift over each letter.'),
        // '#element_validate' => array('element_validate_integer_positive', 'element_validate_shift_range'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Choose to shift either right or left.'),
        // '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['cipher_phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please choose a phrase to encrypt.'),
        // '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );
    return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['shift_direction'];
    $phrase = strtolower($form_state['values']['cipher_phrase']);

    $alphabet = array(
        'a' => '0',
        'b' => '1',
        'c' => '2',
        'd' => '3',
        'e' => '4',
        'f' => '5',
        'g' => '6',
        'h' => '7',
        'i' => '8',
        'j' => '9',
        'k' => '10',
        'l' => '11',
        'm' => '12',
        'n' => '13',
        'o' => '14',
        'p' => '15',
        'q' => '16',
        'r' => '17',
        's' => '18',
        't' => '19',
        'u' => '20',
        'v' => '21',
        'w' => '22',
        'x' => '23',
        'y' => '24',
        'z' => '25',
    );

    $new_phrase = array();

    for($i = 0; $i < strlen($phrase); $i++) {
        if ($direction = 'right') {
            foreach($alphabet as $key => $value) {
                if ($key === $phrase[$i]) {
                    $shift_reference = $value + $shift_value;
                    array_push($new_phrase, $alphabet['$shift_reference']);
                } else {
                    array_push($new_phrase, $phrase[$i]);
                }
            }
        } else {
            foreach($alphabet as $key => $value) {
                if ($key === $phrase[$i]) {
                    $shift_reference = $value - $shift_value;
                    array_push($new_phrase, $alphabet['$shift_reference']);
                } else {
                    array_push($new_phrase, $phrase[$i]);
                }
            }

        }
    }


    $_SESSION['shift_cypher_output'] = $new_phrase;
    $form_state['redirect'] = 'cipher_success';
}

function shift_cipher_success() {
    $results = $_SESSION['shift_cypher_output'];
    return $results;
}
