<?php

function shift_cipher_menu() {
    $items = array();
    $items['shift_cipher'] = array(
        'title' => 'Shift Cipher',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
    );
    $items['cipher_success'] = array(
        'title' => 'Shift Cipher Results Page',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'shift_cipher_success',
    );
    return $items;
}

function shift_cipher_form() {
    $form = array();
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('The number of places to shift over each letter.'),
        // '#element_validate' => array('element_validate_integer_positive', 'element_validate_shift_range'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Choose to shift either right or left.'),
        // '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['cipher_phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please choose a phrase to encrypt.'),
        // '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );
    return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
    $value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['shift_direction'];
    $phrase = $form_state['values']['cipher_phrase'];

    $_SESSION['shift_cypher_output'] = $value . $direction . $phrase;
    $form_state['redirect'] = 'cipher_success';
}

function shift_cipher_success() {
    $results = $_SESSION['shift_cypher_output'];
    return $results;
}
